// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hyccmnrksntspxbhmefh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh5Y2NtbnJrc250c3B4YmhtZWZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE5OTg4NzcsImV4cCI6MjA1NzU3NDg3N30.82Wb7_0FGN_XJMilT0X3hIhRQmtbRM6O2mSkTlmAEjE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);